# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: version-check
        name: Check version increment
        entry: check_project_version
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
        additional_dependencies: ['DXEntity', 'PyYAML']
